### PR TITLE
Module3 wording edits

### PR DESCRIPTION
**Pull request by devin-donnelly**
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/kubernetes-bootcamp/38)

### CODE REVIEW

**Comment by pwittrock** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[3-1.html, line 223 \[r1\]](https://reviewable.io:443/reviews/kubernetes/kubernetes-bootcamp/38#-KPtv-jsUOKatXIaZawl:-KPtv-jsUOKatXIaZawm:b-6z69hq) ([raw file](https://github.com/kubernetes/kubernetes-bootcamp/blob/922786a6884ba3a01158f74dd99a3ad349dbd298/3-1.html#L223)):*
> ```HTML
> 					<li>Information about how to run each container, such as the container image version or specific ports to use</li>
> 				</ul> 
> 				<p>A Pod models an application-specific “logical host” and can contain different application containers which are relatively tightly coupled. For example, a Pod might include both the container with your NodeJS app as well as a different container that feeds the data to be published by the NodeJS webserver. The containers in a Pod share an IP Address and port space, are always co-located and co-scheduled, and run in a shared context on the same Node.</p>
> ```

WDYT of replacing "different" with "supporting"?

---

*[3-1.html, line 225 \[r1\]](https://reviewable.io:443/reviews/kubernetes/kubernetes-bootcamp/38#-KPtvA9cCnfE5TgAxZ2T:-KPtvA9cCnfE5TgAxZ2U:b-xaxfyf) ([raw file](https://github.com/kubernetes/kubernetes-bootcamp/blob/922786a6884ba3a01158f74dd99a3ad349dbd298/3-1.html#L225)):*
> ```HTML
> 				<p>A Pod models an application-specific “logical host” and can contain different application containers which are relatively tightly coupled. For example, a Pod might include both the container with your NodeJS app as well as a different container that feeds the data to be published by the NodeJS webserver. The containers in a Pod share an IP Address and port space, are always co-located and co-scheduled, and run in a shared context on the same Node.</p>
> 
> 			<p>Pods are the atomic deployment unit on the Kubernetes platform. When we create a Deployment on Kubernetes, that Deployment creates Pods with containers inside them (as opposed to creating containers directly). Each Pod is tied to the Node where it is deployed, and remains there until termination (according to restart policy) or deletion. In case of a Node failure, identical Pods are deployed on other available Nodes in the cluster.</p>
> ```

nit: Is it confusing to use the word "deployment" here since it has a different meaning than "Deployment".  Same for "where it is deployed" => "where it is scheduled"?

---

*[3-1.html, line 262 \[r1\]](https://reviewable.io:443/reviews/kubernetes/kubernetes-bootcamp/38#-KPtsw-Ofz77FzaY5MCD:-KPtsw-Ofz77FzaY5MCE:bozvo8c) ([raw file](https://github.com/kubernetes/kubernetes-bootcamp/blob/922786a6884ba3a01158f74dd99a3ad349dbd298/3-1.html#L262)):*
> Nodes

Node

---

*[3-1.html, line 267 \[r1\]](https://reviewable.io:443/reviews/kubernetes/kubernetes-bootcamp/38#-KPtuA9QWgPuPMYRW9Sn:-KPtuA9QWgPuPMYRW9So:bkiz4c1) ([raw file](https://github.com/kubernetes/kubernetes-bootcamp/blob/922786a6884ba3a01158f74dd99a3ad349dbd298/3-1.html#L267)):*
> ```HTML
> 				<ul>
> 					<li>Kubelet, a process responsible for communication between the Kubernetes Master and the Nodes; it manages the Pods and the containers running on a machine.</li>
> 					<li>A container runtime (like Docker, rkt) responsible for pulling all of your containers from a registry.</li>
> ```

FYI the container runtime also runs the containers in addition to pulling the images.  We should also probably be clear on the difference between the container image (binary packaging of files) and the running container (the unpacked files + running processes and machine resources).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/kubernetes-bootcamp/38)*

**Comment by devin-donnelly** [comment]
*[3-1.html, line 223 \[r1\]](https://reviewable.io:443/reviews/kubernetes/kubernetes-bootcamp/38#-KPtv-jsUOKatXIaZawl:-KPxlMfAhknrDV6nDNqm:b-f6ccug) ([raw file](https://github.com/kubernetes/kubernetes-bootcamp/blob/4219fdcdfedc41c8e851907c27315a0af09dfb8b/3-1.html#L223)):*
<details><summary><i>Previously, pwittrock (Phillip Wittrock) wrote…</i></summary>
> WDYT of replacing "different" with "supporting"?
</details>
I see what you're getting at, but "supporting" is a little ambiguous (and the statement "that are relatively tightly coupled" expresses that idea. The point I was getting is that it isn't entirely clear that all the containers in a Pod aren't just copies of the same container; they're different containers with reason to be logically grouped.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/kubernetes-bootcamp/38)*

**Comment by devin-donnelly** [comment]
*[3-1.html, line 225 \[r1\]](https://reviewable.io:443/reviews/kubernetes/kubernetes-bootcamp/38#-KPtvA9cCnfE5TgAxZ2T:-KPxlyph30BNqjkJCL3V:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes-bootcamp/blob/4219fdcdfedc41c8e851907c27315a0af09dfb8b/3-1.html#L225)):*
<details><summary><i>Previously, pwittrock (Phillip Wittrock) wrote…</i></summary>
> nit: Is it confusing to use the word "deployment" here since it has a different meaning than "Deployment".  Same for "where it is deployed" => "where it is scheduled"?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/kubernetes-bootcamp/38)*

**Comment by devin-donnelly** [comment]
*[3-1.html, line 262 \[r1\]](https://reviewable.io:443/reviews/kubernetes/kubernetes-bootcamp/38#-KPtsw-Ofz77FzaY5MCD:-KPxmP2lT556Z_jVLljH:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes-bootcamp/blob/4219fdcdfedc41c8e851907c27315a0af09dfb8b/3-1.html#L262)):*
<details><summary><i>Previously, pwittrock (Phillip Wittrock) wrote…</i></summary>
> > Nodes
> 
> Node
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/kubernetes-bootcamp/38)*

**Comment by devin-donnelly** [comment]
*[3-1.html, line 267 \[r1\]](https://reviewable.io:443/reviews/kubernetes/kubernetes-bootcamp/38#-KPtuA9QWgPuPMYRW9Sn:-KPxmcIItzah0gPalutQ:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes-bootcamp/blob/4219fdcdfedc41c8e851907c27315a0af09dfb8b/3-1.html#L267)):*
<details><summary><i>Previously, pwittrock (Phillip Wittrock) wrote…</i></summary>
> FYI the container runtime also runs the containers in addition to pulling the images.  We should also probably be clear on the difference between the container image (binary packaging of files) and the running container (the unpacked files + running processes and machine resources).
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/kubernetes-bootcamp/38)*

**Comment by pwittrock** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/kubernetes-bootcamp/38#-:-KPydGmDi7KhWNYu8AtZ:bnfp4nl)*

**Comment by pwittrock** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/kubernetes-bootcamp/38)*

**Pull request merged**
