### PR TITLE
Made some edits to the wording in Module 1.

### PR DESCRIPTION
**Pull request by devin-donnelly**
This change is [Reviewable](https://reviewable.io/reviews/kubernetes/kubernetes-bootcamp/34)

### CODE REVIEW

**Comment by devin-donnelly** [comment]
*[1-1.html, line 272 \[r1\]](https://reviewable.io:443/reviews/kubernetes/kubernetes-bootcamp/34#-KPPeufZUoOC9WWPQYjm:-KPPeufZUoOC9WWPQYjn:b-vl9ch3) ([raw file](https://github.com/kubernetes/kubernetes-bootcamp/blob/80b9f3fc1671deb8ecad6bf934145b1578b1b2a4/1-1.html#L272)):*
> ```HTML
> 		<div class="row">
> 			<div class="col-md-8">
> 				<p>When you deploy applications on Kubernetes, you tell the master to start the application containers. The master schedules the containers to run on the cluster's nodes. <b>The master exposes an API that enabes communication between the master and the nodes;</b> that same API is exposed to users, who can use it to interact with the cluster as a whole.</p>
> ```

Should we actually call this API out by name? As in, "the master exposes an API called ..." Otherwise it just seems weird. "Trust us, there's an API."

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/kubernetes-bootcamp/34)*

**Comment by pwittrock** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[1-1.html, line 272 \[r1\]](https://reviewable.io:443/reviews/kubernetes/kubernetes-bootcamp/34#-KPPeufZUoOC9WWPQYjm:-KPPgAfAy87R0GgDFRRB:bain5hx) ([raw file](https://github.com/kubernetes/kubernetes-bootcamp/blob/80b9f3fc1671deb8ecad6bf934145b1578b1b2a4/1-1.html#L272)):*
We refer to it as the `Kubernetes API` here: http://kubernetes.io/docs/api/

Maybe something like:

>
Both end users and nodes use the Kubernetes API, exposed by the master, to interact with the cluster.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/kubernetes-bootcamp/34)*

**Comment by devin-donnelly** [comment]
*[1-1.html, line 272 \[r1\]](https://reviewable.io:443/reviews/kubernetes/kubernetes-bootcamp/34#-KPPeufZUoOC9WWPQYjm:-KPUasOCNrnRG0zCIggE:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes-bootcamp/blob/80b9f3fc1671deb8ecad6bf934145b1578b1b2a4/1-1.html#L272)):*
<details><summary><i>Previously, pwittrock (Phillip Wittrock) wrote…</i></summary>
> We refer to it as the `Kubernetes API` here: http://kubernetes.io/docs/api/
> 
> Maybe something like:
> 
> >
> Both end users and nodes use the Kubernetes API, exposed by the master, to interact with the cluster.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/kubernetes-bootcamp/34)*

**Comment by pwittrock** [comment]
:lgtm: 

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kubernetes/kubernetes-bootcamp/34#-:-KPUe1OKlQBgNmjBC3Pt:bg7igkv)*

**Pull request merged**
